"""Structural type of SQLiteCurrentStateRepository that its responsibility mixins rely on."""

from __future__ import annotations

import sqlite3
from collections.abc import Mapping
from datetime import datetime
from typing import Protocol

from ehai import ID
from ehai.application.process_obligations import ProcessObligationMapping
from ehai.domain.adoptions import ResultAdoption
from ehai.domain.artifacts import Artifact
from ehai.domain.checking import Checkpoint, CheckRun, CheckSpec
from ehai.domain.execution import Attempt, Run
from ehai.domain.goal import CompletionContract, Goal, Project
from ehai.domain.planning import (
    PlanNode,
    PlanRevision,
)
from ehai.domain.process import (
    ProcessRevision,
)
from ehai.domain.process_drafts import (
    ProcessDraft,
)
from ehai.domain.runtime import DispatchWork, DispatchWorkStatus
from ehai.domain.workers import (
    AgentSessionRef,
    BuiltinExecutionRef,
    ExternalExecutionRef,
)


class StateRepositoryHost(Protocol):
    """Members of ``SQLiteCurrentStateRepository``; mypy checks the class against it."""

    _connection: sqlite3.Connection

    def put_project(self, project: Project) -> None: ...

    def get_project(self, project_id: ID) -> Project | None: ...

    def list_projects(self) -> tuple[Project, ...]: ...

    def put_goal(self, goal: Goal) -> None: ...

    def get_goal(self, goal_id: ID) -> Goal | None: ...

    def list_goals(self, project_id: ID) -> tuple[Goal, ...]: ...

    def put_completion_contract(self, contract: CompletionContract) -> None: ...

    def get_completion_contract(self, completion_contract_id: ID) -> CompletionContract | None: ...

    def list_completion_contracts(self, goal_id: ID) -> tuple[CompletionContract, ...]: ...

    def put_plan_revision(self, plan_revision: PlanRevision) -> None: ...

    def get_plan_revision(self, plan_revision_id: ID) -> PlanRevision | None: ...

    def list_plan_revisions(self, goal_id: ID) -> tuple[PlanRevision, ...]: ...

    def get_execution_plan(self, run_id: ID) -> PlanRevision | None: ...

    def put_execution_plan(self, run_id: ID, plan_revision: PlanRevision) -> None: ...

    def get_process_revision(self, process_revision_id: ID) -> ProcessRevision | None: ...

    def get_process_draft(self, draft_id: ID) -> ProcessDraft | None: ...

    def list_process_drafts(self, run_id: ID) -> tuple[ProcessDraft, ...]: ...

    def get_result_adoption(self, adoption_id: ID) -> ResultAdoption | None: ...

    def list_result_adoptions(self, target_run_id: ID) -> tuple[ResultAdoption, ...]: ...

    def put_result_adoption(self, record: ResultAdoption) -> None: ...

    def put_process_draft(self, draft: ProcessDraft) -> None: ...

    def publish_process_revision(
        self,
        revision: ProcessRevision,
        *,
        expected_current: PlanRevision,
        obligation_mapping: ProcessObligationMapping,
        source_documents: Mapping[str, str],
    ) -> None: ...

    def _validate_retained_process_selections(
        self, run_id: ID, current: PlanRevision, proposed: PlanRevision
    ) -> None: ...

    def _insert_process_members(self, current: PlanRevision, proposed: PlanRevision) -> None: ...

    def get_active_process_revision(self, run_id: ID) -> ProcessRevision | None: ...

    def put_run(self, run: Run) -> None: ...

    def get_run(self, run_id: ID) -> Run | None: ...

    def list_runs(self, goal_id: ID) -> tuple[Run, ...]: ...

    def put_attempt(self, attempt: Attempt) -> None: ...

    def get_attempt(self, attempt_id: ID) -> Attempt | None: ...

    def list_attempts(self, run_id: ID) -> tuple[Attempt, ...]: ...

    def put_dispatch_work(self, work: DispatchWork) -> None: ...

    def get_dispatch_work(self, dispatch_work_id: ID) -> DispatchWork | None: ...

    def list_dispatch_work(
        self, status: DispatchWorkStatus | None = ...
    ) -> tuple[DispatchWork, ...]: ...

    def claim_next_dispatch_work(
        self, *, owner: str, at: datetime, lease_expires_at: datetime
    ) -> DispatchWork | None: ...

    def record_worker_event(
        self, attempt_id: ID, worker_event_id: str, *, at: datetime
    ) -> bool: ...

    def put_agent_session_ref(self, session: AgentSessionRef) -> None: ...

    def get_agent_session_ref(self, agent_session_ref_id: ID) -> AgentSessionRef | None: ...

    def list_agent_session_refs(self, run_id: ID) -> tuple[AgentSessionRef, ...]: ...

    def put_external_execution_ref(self, reference: ExternalExecutionRef) -> None: ...

    def get_external_execution_ref(
        self, external_execution_ref_id: ID
    ) -> ExternalExecutionRef | None: ...

    def put_builtin_execution_ref(self, reference: BuiltinExecutionRef) -> None: ...

    def get_builtin_execution_ref(
        self, builtin_execution_ref_id: ID
    ) -> BuiltinExecutionRef | None: ...

    def _validate_attempt_runtime_refs(self, attempt: Attempt) -> None: ...

    def _validate_execution_reference(
        self, attempt_id: ID, agent_session_ref_id: ID, *, expected_builtin: bool
    ) -> None: ...

    def put_check_spec(self, plan_revision_id: ID, check_spec: CheckSpec) -> None: ...

    def get_check_spec(self, check_id: ID) -> CheckSpec | None: ...

    def list_check_specs(self, plan_revision_id: ID) -> tuple[CheckSpec, ...]: ...

    def put_check_run(self, check_run: CheckRun) -> None: ...

    def _validate_human_check_run(
        self, check_run: CheckRun, run: Run, node: PlanNode, attempt: Attempt
    ) -> None: ...

    def get_check_run(self, check_run_id: ID) -> CheckRun | None: ...

    def list_check_runs(self, run_id: ID) -> tuple[CheckRun, ...]: ...

    def put_checkpoint(self, checkpoint: Checkpoint) -> None: ...

    def get_checkpoint(self, checkpoint_id: ID) -> Checkpoint | None: ...

    def list_checkpoints(self, run_id: ID) -> tuple[Checkpoint, ...]: ...

    def restore_checkpoint_state(self, checkpoint: Checkpoint, restored_run: Run) -> None: ...

    def put_artifact(self, artifact: Artifact) -> None: ...

    def _adoption_verification(
        self, run: Run, node_id: ID, attempt: Attempt, adoption_id: ID
    ) -> ResultAdoption: ...

    def _validate_result_adoption(self, record: ResultAdoption) -> None: ...

    def get_artifact(self, artifact_id: ID) -> Artifact | None: ...

    def list_artifacts_for_run(self, run_id: ID) -> tuple[Artifact, ...]: ...

    def _validate_plan_update(self, plan_revision: PlanRevision) -> None: ...

    def _validate_new_process_draft(self, draft: ProcessDraft) -> None: ...

    def _validate_process_draft_update(
        self, existing: ProcessDraft, draft: ProcessDraft
    ) -> None: ...

    def _validate_process_draft_candidate(self, draft: ProcessDraft) -> None: ...

    def _validate_graph_update(
        self, existing: PlanRevision, plan_revision: PlanRevision, *, run_id: ID | None = ...
    ) -> None: ...

    def _validate_checkpoint_references(self, checkpoint: Checkpoint) -> None: ...

    def _validate_plan_child_identity(self, plan_revision: PlanRevision) -> None: ...

    def _snapshot(self, table: str, id_column: str, entity_id: ID) -> str | None: ...

    def _decode_process_draft_row(self, row: sqlite3.Row) -> ProcessDraft: ...

    def _decode_result_adoption_row(self, row: sqlite3.Row) -> ResultAdoption: ...

    def _snapshots(self, sql: str, parameters: tuple[object, ...] = ...) -> tuple[str, ...]: ...

    def _strings(self, sql: str, parameters: tuple[object, ...]) -> tuple[str, ...]: ...

    def _required_goal(self, goal_id: ID) -> Goal: ...

    def _required_run(self, run_id: ID) -> Run: ...

    def _required_attempt(self, attempt_id: ID) -> Attempt: ...

    def _required_plan_revision(self, plan_revision_id: ID) -> PlanRevision: ...

    def _required_execution_plan(self, run_id: ID) -> PlanRevision: ...

    def _required_active_process_revision(self, run_id: ID) -> ProcessRevision: ...

    def _attempt_plan(self, attempt: Attempt) -> PlanRevision: ...
